[tool.pyright]
exclude = ["**/__pycache__", "**/build", "venv"]


[tool.ruff]
line-length = 88
target-version = "py310"
force-exclude = true

[tool.ruff.lint]
preview = true
select = [
  "F402",
  "F404",
  "F823",
  "F821",
  "F822",
  "E112",
  "E113",
  "E902",
]
